[package]
name = "thms"
version = "0.2.0"
entrypoint = "lib.typ"
authors = ["crd2333"]
license = "MIT"
repository = "https://github.com/crd2333/typst-theorem-box"
description = "A theorem box designed using showybox."